<a href="https://colab.research.google.com/github/Madhav7871/Movie_Recommendation_System/blob/main/Movie_Recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from IPython.display import display

In [2]:
df = pd.read_csv("/content/drive/MyDrive/data/imdb_top_movies_1980_2026.csv")

In [3]:
df.head()

,imdb_id,title,original_title,year,runtime_minutes,genres,average_rating,num_votes,imdb_url
0,tt0111161,The Shawshank Redemption,The Shawshank Redemption,1994,142.0,Drama,9.3,3182733,https://www.imdb.com/title/tt0111161
1,tt0468569,The Dark Knight,The Dark Knight,2008,152.0,"Action,Crime,Drama",9.1,3161984,https://www.imdb.com/title/tt0468569
2,tt1375666,Inception,Inception,2010,148.0,"Action,Adventure,Sci-Fi",8.8,2811692,https://www.imdb.com/title/tt1375666
3,tt0137523,Fight Club,Fight Club,1999,139.0,"Crime,Drama,Thriller",8.8,2601984,https://www.imdb.com/title/tt0137523
4,tt0816692,Interstellar,Interstellar,2014,169.0,"Adventure,Drama,Sci-Fi",8.7,2521607,https://www.imdb.com/title/tt0816692

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16252 entries, 0 to 16251
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   imdb_id          16252 non-null  object
 1   title            16252 non-null  object
 2   original_title   16252 non-null  object
 3   year             16252 non-null  int64
 4   runtime_minutes  16251 non-null  float64
 5   genres           16246 non-null  object
 6   average_rating   16252 non-null  float64
 7   num_votes        16252 non-null  int64
 8   imdb_url         16252 non-null  object
dtypes: float64(2), int64(2), object(5)
memory usage: 1.1+ MB

In [5]:
df.columns

Index(['imdb_id', 'title', 'original_title', 'year', 'runtime_minutes',
       'genres', 'average_rating', 'num_votes', 'imdb_url'],
      dtype='object')

In [6]:
df.nunique()

imdb_id            16252
title              15629
original_title     15811
year                  47
runtime_minutes      180
genres               505
average_rating        82
num_votes          13307
imdb_url           16252
dtype: int64

In [7]:
df.shape

(16252, 9)

In [21]:
df['genres'] = df['genres'].fillna('')
tfidf = TfidfVectorizer(stop_words='english')
genre_matrix = tfidf.fit_transform(df['genres'])
cosine_sim = cosine_similarity(genre_matrix, genre_matrix)
indices = pd.Series(df.index, index=df['title'].str.lower()).drop_duplicates()
def recommend(movie_title, top_n=10):
    movie_title = movie_title.lower()
    if movie_title not in indices:
        return "Movie not found."
    idx = indices[movie_title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_df = df.iloc[[i[0] for i in sim_scores]].copy()
    sim_df['similarity_score'] = [i[1] for i in sim_scores]
    candidates = sim_df.sort_values(by='similarity_score', ascending=False).iloc[1:51]
    recommendations = candidates.sort_values(by='average_rating', ascending=False).head(top_n)
    return recommendations[['title', 'genres', 'average_rating', 'num_votes']]
movie_name = input("Enter a movie name: ")
recommendations = recommend(movie_name)
if isinstance(recommendations, pd.DataFrame):
    display(recommendations.reset_index(drop=True).style.hide(axis='index'))
else:
    print(recommendations)

Enter a movie name: The Dark Knight